import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {validateConfiguration,configurationEnvelope,sendToTarget,deliverNotifications,__test__} from '../plugin-packages/multi-platform-notify/main.js';

const NOW=Date.now();
const event={id:'notice-1',kind:'class',title:'高等数学',body:'08:00–09:35\n教学楼 A101',sourceId:'schedule',sourceName:'课表',expiresAt:NOW+3600000};
const target=(id,platform='feishu')=>({id,name:id,platform,url:platform==='wecom'?'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=demo':platform==='dingtalk'?'https://oapi.dingtalk.com/robot/send?access_token=demo':'https://open.feishu.cn/open-apis/bot/v2/hook/demo',enabled:true,kinds:['class'],secret:''});
function ctx(config,{response=()=>({code:0}),receipts=[]}={}){const calls=[],acks=[];return{calls,acks,now:()=>NOW,secureConfiguration:{targets:config},notifications:[{notification:event,targetIds:config.map(x=>x.id),receipts}],notification:{async receipt(...args){acks.push(args);}},crypto:{async hmacSha256(key,message){return createHmac('sha256',key).update(message).digest('base64');}},network:{async fetch(url,init){calls.push({url,init,body:JSON.parse(init.body)});return{ok:true,status:200,json:async()=>response(url,init)};}}};}

test('绑定模型支持同平台多目标，宿主摘要不含 Webhook 与密钥',()=>{const config=[target('one'),target('two')];config[0].secret='private-secret';const envelope=configurationEnvelope({targets:config});assert.equal(envelope.targets.length,2);assert.deepEqual(envelope.hosts,['open.feishu.cn']);assert.equal(JSON.stringify(envelope.targets).includes('private-secret'),false);assert.equal(JSON.stringify(envelope.targets).includes('http'),false);});
test('非 HTTPS、伪造平台域名、重复 ID 和空范围不能保存',()=>{for(const changed of [{url:'http://open.feishu.cn/open-apis/bot/v2/hook/a'},{url:'https://open.feishu.cn.evil.example/open-apis/bot/v2/hook/a'},{kinds:[]},{token:'secret\nheader'}])assert.throws(()=>validateConfiguration({targets:[{...target('one'),...changed}]}));assert.throws(()=>validateConfiguration({targets:[target('one'),target('one')]}));});
test('飞书签名按秒时间戳加密空字符串，不套用钉钉签名算法',async()=>{const t={...target('one'),secret:'test-secret'};const c=ctx([t]);await sendToTarget(c,t,event);const body=c.calls[0].body;assert.equal(body.timestamp,String(Math.floor(NOW/1000)));assert.equal(body.sign,createHmac('sha256',body.timestamp+'\ntest-secret').update('').digest('base64'));assert.equal(body.msg_type,'text');});
test('钉钉签名按毫秒时间戳并做 URL 编码',async()=>{const t={...target('ding','dingtalk'),secret:'SEC-demo'};const c=ctx([t],{response:()=>({errcode:0})});await sendToTarget(c,t,event);const u=new URL(c.calls[0].url);assert.equal(u.searchParams.get('timestamp'),String(NOW));assert.equal(u.searchParams.get('sign'),createHmac('sha256','SEC-demo').update(String(NOW)+'\nSEC-demo').digest('base64'));});
test('企业微信按 UTF-8 字节裁剪长正文且不破坏中文',async()=>{const t=target('wecom','wecom'),c=ctx([t],{response:()=>({errcode:0})});await sendToTarget(c,t,{...event,body:'任务🙂'.repeat(900)});const text=c.calls[0].body.text.content;assert.ok(Buffer.byteLength(text)<=1800);assert.ok(text.endsWith('…'));assert.equal(text.includes('\uFFFD'),false);});
test('HTTP 成功但平台拒绝仍记录失败，其他目标继续发送',async()=>{const c=ctx([target('one'),target('two')],{response:(_,init)=>JSON.parse(init.body).content.text.includes('anything')?{code:0}:{code:19021}});let calls=0;c.network.fetch=async(url,init)=>{const code=++calls===1?19021:0;return {ok:true,status:200,json:async()=>({code})};};const result=await deliverNotifications(c);assert.deepEqual(result,{delivered:1,failed:1});assert.ok(c.acks.some(x=>x[1]==='one'&&x[2]==='failed'));assert.ok(c.acks.some(x=>x[1]==='two'&&x[2]==='sent'));});
test('部分重试跳过已成功或未确认的目标，暂停目标不会发送',async()=>{const c=ctx([target('one'),target('two'),{...target('three'),enabled:false}],{receipts:[{targetId:'one',status:'sent'},{targetId:'two',status:'unknown'}]});await deliverNotifications(c);assert.equal(c.calls.length,0);assert.ok(c.acks.some(x=>x[1]==='three'&&x[2]==='skipped'));});
test('网络结果未知时停止自动重发',async()=>{const c=ctx([target('one')]);c.network.fetch=async()=>({ok:false,status:0,ambiguous:true});await deliverNotifications(c);assert.ok(c.acks.some(x=>x[2]==='unknown'));assert.equal(c.acks.some(x=>x[2]==='sent'),false);});
test('平台接受但回执保存失败也标为未确认',async()=>{const c=ctx([target('one')]);c.notification.receipt=async(...args)=>{if(args[2]==='sent')throw new Error('storage unavailable');c.acks.push(args);};await deliverNotifications(c);assert.ok(c.acks.some(x=>x[2]==='unknown'));assert.equal(c.acks.some(x=>x[2]==='failed'),false);});
test('OpenClaw 使用固定路由与 Bearer 令牌，不传可执行命令',async()=>{const t={...target('qq'),platform:'qq',url:'https://notify.example/v1/notify',routeId:'qq-private',token:'demo-token'};const c=ctx([t],{response:()=>({ok:true,delivered:true})});await sendToTarget(c,t,event,true);assert.equal(c.calls[0].init.headers.Authorization,'Bearer demo-token');assert.equal(c.calls[0].body.routeId,'qq-private');assert.equal(c.calls[0].body.force,true);assert.equal(c.calls[0].body.command,undefined);});
test('标题模式不会泄露正文，通用 Webhook 需要明确确认',async()=>{const t={...target('webhook'),platform:'webhook',url:'https://notify.example/notify',includeBody:false};const c=ctx([t],{response:()=>({ok:true})});await sendToTarget(c,t,event);assert.equal(c.calls[0].body.body,'');c.network.fetch=async()=>({ok:true,status:200,json:async()=>({})});await assert.rejects(sendToTarget(c,t,event),/确认/);});
test('UTF-8 边界不拆分表情字符',()=>{const output=__test__.truncateUtf8('🙂🙂🙂',10);assert.equal(output,'🙂…');});
